using System.Collections.Generic;

namespace ProjectIndustries.ProjectRaffles.Core.Services.FormParsers.MailChimp.Landing.Fields
{
  public class MailChildCountries
  {
    public static IReadOnlyList<KeyValuePair<string, string>> Countries = new List<KeyValuePair<string, string>>
      {
        new KeyValuePair<string, string>("Aaland Islands", "286"),
        new KeyValuePair<string, string>("Afghanistan", "274"),
        new KeyValuePair<string, string>("Albania", "2"),
        new KeyValuePair<string, string>("Algeria", "3"),
        new KeyValuePair<string, string>("American Samoa", "178"),
        new KeyValuePair<string, string>("Andorra", "4"),
        new KeyValuePair<string, string>("Angola", "5"),
        new KeyValuePair<string, string>("Anguilla", "176"),
        new KeyValuePair<string, string>("Antigua And Barbuda", "175"),
        new KeyValuePair<string, string>("Argentina", "6"),
        new KeyValuePair<string, string>("Armenia", "7"),
        new KeyValuePair<string, string>("Aruba", "179"),
        new KeyValuePair<string, string>("Australia", "8"),
        new KeyValuePair<string, string>("Austria", "9"),
        new KeyValuePair<string, string>("Azerbaijan", "10"),
        new KeyValuePair<string, string>("Bahamas", "11"),
        new KeyValuePair<string, string>("Bahrain", "12"),
        new KeyValuePair<string, string>("Bangladesh", "13"),
        new KeyValuePair<string, string>("Barbados", "14"),
        new KeyValuePair<string, string>("Belarus", "15"),
        new KeyValuePair<string, string>("Belgium", "16"),
        new KeyValuePair<string, string>("Belize", "17"),
        new KeyValuePair<string, string>("Benin", "18"),
        new KeyValuePair<string, string>("Bermuda", "19"),
        new KeyValuePair<string, string>("Bhutan", "20"),
        new KeyValuePair<string, string>("Bolivia", "21"),
        new KeyValuePair<string, string>("Bosnia and Herzegovina", "22"),
        new KeyValuePair<string, string>("Botswana", "23"),
        new KeyValuePair<string, string>("Bouvet Island", "181"),
        new KeyValuePair<string, string>("Brazil", "24"),
        new KeyValuePair<string, string>("Brunei Darussalam", "180"),
        new KeyValuePair<string, string>("Bulgaria", "25"),
        new KeyValuePair<string, string>("Burkina Faso", "26"),
        new KeyValuePair<string, string>("Burundi", "27"),
        new KeyValuePair<string, string>("Cambodia", "28"),
        new KeyValuePair<string, string>("Cameroon", "29"),
        new KeyValuePair<string, string>("Canada", "30"),
        new KeyValuePair<string, string>("Cape Verde", "31"),
        new KeyValuePair<string, string>("Cayman Islands", "32"),
        new KeyValuePair<string, string>("Central African Republic", "33"),
        new KeyValuePair<string, string>("Chad", "34"),
        new KeyValuePair<string, string>("Chile", "35"),
        new KeyValuePair<string, string>("China", "36"),
        new KeyValuePair<string, string>("Christmas Island", "185"),
        new KeyValuePair<string, string>("Colombia", "37"),
        new KeyValuePair<string, string>("Comoros", "204"),
        new KeyValuePair<string, string>("Congo", "38"),
        new KeyValuePair<string, string>("Cook Islands", "183"),
        new KeyValuePair<string, string>("Costa Rica", "268"),
        new KeyValuePair<string, string>("Cote D'Ivoire", "275"),
        new KeyValuePair<string, string>("Croatia", "40"),
        new KeyValuePair<string, string>("Cuba", "276"),
        new KeyValuePair<string, string>("Curacao", "298"),
        new KeyValuePair<string, string>("Cyprus", "41"),
        new KeyValuePair<string, string>("Czech Republic", "42"),
        new KeyValuePair<string, string>("Denmark", "43"),
        new KeyValuePair<string, string>("Djibouti", "44"),
        new KeyValuePair<string, string>("Dominica", "289"),
        new KeyValuePair<string, string>("Dominican Republic", "187"),
        new KeyValuePair<string, string>("East Timor", "233"),
        new KeyValuePair<string, string>("Ecuador", "45"),
        new KeyValuePair<string, string>("Egypt", "46"),
        new KeyValuePair<string, string>("El Salvador", "47"),
        new KeyValuePair<string, string>("Equatorial Guinea", "48"),
        new KeyValuePair<string, string>("Eritrea", "49"),
        new KeyValuePair<string, string>("Estonia", "50"),
        new KeyValuePair<string, string>("Ethiopia", "51"),
        new KeyValuePair<string, string>("Falkland Islands", "189"),
        new KeyValuePair<string, string>("Faroe Islands", "191"),
        new KeyValuePair<string, string>("Fiji", "52"),
        new KeyValuePair<string, string>("Finland", "53"),
        new KeyValuePair<string, string>("France", "54"),
        new KeyValuePair<string, string>("French Guiana", "193"),
        new KeyValuePair<string, string>("French Polynesia", "277"),
        new KeyValuePair<string, string>("Gabon", "56"),
        new KeyValuePair<string, string>("Gambia", "57"),
        new KeyValuePair<string, string>("Georgia", "58"),
        new KeyValuePair<string, string>("Germany", "59"),
        new KeyValuePair<string, string>("Ghana", "60"),
        new KeyValuePair<string, string>("Gibraltar", "194"),
        new KeyValuePair<string, string>("Greece", "61"),
        new KeyValuePair<string, string>("Greenland", "195"),
        new KeyValuePair<string, string>("Grenada", "192"),
        new KeyValuePair<string, string>("Guadeloupe", "196"),
        new KeyValuePair<string, string>("Guam", "62"),
        new KeyValuePair<string, string>("Guatemala", "198"),
        new KeyValuePair<string, string>("Guernsey", "270"),
        new KeyValuePair<string, string>("Guinea", "63"),
        new KeyValuePair<string, string>("Guyana", "65"),
        new KeyValuePair<string, string>("Haiti", "200"),
        new KeyValuePair<string, string>("Honduras", "66"),
        new KeyValuePair<string, string>("Hong Kong", "67"),
        new KeyValuePair<string, string>("Hungary", "68"),
        new KeyValuePair<string, string>("Iceland", "69"),
        new KeyValuePair<string, string>("India", "70"),
        new KeyValuePair<string, string>("Indonesia", "71"),
        new KeyValuePair<string, string>("Iran", "278"),
        new KeyValuePair<string, string>("Iraq", "279"),
        new KeyValuePair<string, string>("Ireland", "74"),
        new KeyValuePair<string, string>("Israel", "75"),
        new KeyValuePair<string, string>("Italy", "76"),
        new KeyValuePair<string, string>("Jamaica", "202"),
        new KeyValuePair<string, string>("Japan", "78"),
        new KeyValuePair<string, string>("Jersey (Channel Islands)", "288"),
        new KeyValuePair<string, string>("Jordan", "79"),
        new KeyValuePair<string, string>("Kazakhstan", "80"),
        new KeyValuePair<string, string>("Kenya", "81"),
        new KeyValuePair<string, string>("Kiribati", "203"),
        new KeyValuePair<string, string>("Kuwait", "82"),
        new KeyValuePair<string, string>("Kyrgyzstan", "83"),
        new KeyValuePair<string, string>("Lao People's Democratic Republic", "84"),
        new KeyValuePair<string, string>("Latvia", "85"),
        new KeyValuePair<string, string>("Lebanon", "86"),
        new KeyValuePair<string, string>("Lesotho", "87"),
        new KeyValuePair<string, string>("Liberia", "88"),
        new KeyValuePair<string, string>("Libya", "281"),
        new KeyValuePair<string, string>("Liechtenstein", "90"),
        new KeyValuePair<string, string>("Lithuania", "91"),
        new KeyValuePair<string, string>("Luxembourg", "92"),
        new KeyValuePair<string, string>("Macau", "208"),
        new KeyValuePair<string, string>("Macedonia", "93"),
        new KeyValuePair<string, string>("Madagascar", "94"),
        new KeyValuePair<string, string>("Malawi", "95"),
        new KeyValuePair<string, string>("Malaysia", "96"),
        new KeyValuePair<string, string>("Maldives", "97"),
        new KeyValuePair<string, string>("Mali", "98"),
        new KeyValuePair<string, string>("Malta", "99"),
        new KeyValuePair<string, string>("Marshall Islands", "207"),
        new KeyValuePair<string, string>("Martinique", "210"),
        new KeyValuePair<string, string>("Mauritania", "100"),
        new KeyValuePair<string, string>("Mauritius", "212"),
        new KeyValuePair<string, string>("Mayotte", "241"),
        new KeyValuePair<string, string>("Mexico", "101"),
        new KeyValuePair<string, string>("Moldova, Republic of", "102"),
        new KeyValuePair<string, string>("Monaco", "103"),
        new KeyValuePair<string, string>("Mongolia", "104"),
        new KeyValuePair<string, string>("Montenegro", "290"),
        new KeyValuePair<string, string>("Montserrat", "294"),
        new KeyValuePair<string, string>("Morocco", "105"),
        new KeyValuePair<string, string>("Mozambique", "106"),
        new KeyValuePair<string, string>("Myanmar", "242"),
        new KeyValuePair<string, string>("Namibia", "107"),
        new KeyValuePair<string, string>("Nepal", "108"),
        new KeyValuePair<string, string>("Netherlands", "109"),
        new KeyValuePair<string, string>("Netherlands Antilles", "110"),
        new KeyValuePair<string, string>("New Caledonia", "213"),
        new KeyValuePair<string, string>("New Zealand", "111"),
        new KeyValuePair<string, string>("Nicaragua", "112"),
        new KeyValuePair<string, string>("Niger", "113"),
        new KeyValuePair<string, string>("Nigeria", "114"),
        new KeyValuePair<string, string>("Niue", "217"),
        new KeyValuePair<string, string>("Norfolk Island", "214"),
        new KeyValuePair<string, string>("North Korea", "272"),
        new KeyValuePair<string, string>("Norway", "116"),
        new KeyValuePair<string, string>("Oman", "117"),
        new KeyValuePair<string, string>("Pakistan", "118"),
        new KeyValuePair<string, string>("Palau", "222"),
        new KeyValuePair<string, string>("Palestine", "282"),
        new KeyValuePair<string, string>("Panama", "119"),
        new KeyValuePair<string, string>("Papua New Guinea", "219"),
        new KeyValuePair<string, string>("Paraguay", "120"),
        new KeyValuePair<string, string>("Peru", "121"),
        new KeyValuePair<string, string>("Philippines", "122"),
        new KeyValuePair<string, string>("Pitcairn", "221"),
        new KeyValuePair<string, string>("Poland", "123"),
        new KeyValuePair<string, string>("Portugal", "124"),
        new KeyValuePair<string, string>("Qatar", "126"),
        new KeyValuePair<string, string>("Republic of Kosovo", "315"),
        new KeyValuePair<string, string>("Reunion", "127"),
        new KeyValuePair<string, string>("Romania", "128"),
        new KeyValuePair<string, string>("Russia", "129"),
        new KeyValuePair<string, string>("Rwanda", "130"),
        new KeyValuePair<string, string>("Saint Kitts and Nevis", "205"),
        new KeyValuePair<string, string>("Saint Lucia", "206"),
        new KeyValuePair<string, string>("Saint Vincent and the Grenadines", "237"),
        new KeyValuePair<string, string>("Samoa (Independent)", "132"),
        new KeyValuePair<string, string>("San Marino", "227"),
        new KeyValuePair<string, string>("Saudi Arabia", "133"),
        new KeyValuePair<string, string>("Senegal", "134"),
        new KeyValuePair<string, string>("Serbia", "266"),
        new KeyValuePair<string, string>("Seychelles", "135"),
        new KeyValuePair<string, string>("Sierra Leone", "136"),
        new KeyValuePair<string, string>("Singapore", "137"),
        new KeyValuePair<string, string>("Sint Maarten", "302"),
        new KeyValuePair<string, string>("Slovakia", "138"),
        new KeyValuePair<string, string>("Slovenia", "139"),
        new KeyValuePair<string, string>("Solomon Islands", "223"),
        new KeyValuePair<string, string>("Somalia", "140"),
        new KeyValuePair<string, string>("South Africa", "141"),
        new KeyValuePair<string, string>("South Georgia and the South Sandwich Islands", "257"),
        new KeyValuePair<string, string>("South Korea", "142"),
        new KeyValuePair<string, string>("South Sudan", "311"),
        new KeyValuePair<string, string>("Spain", "143"),
        new KeyValuePair<string, string>("Sri Lanka", "144"),
        new KeyValuePair<string, string>("Sudan", "293"),
        new KeyValuePair<string, string>("Suriname", "146"),
        new KeyValuePair<string, string>("Svalbard and Jan Mayen Islands", "225"),
        new KeyValuePair<string, string>("Swaziland", "147"),
        new KeyValuePair<string, string>("Sweden", "148"),
        new KeyValuePair<string, string>("Switzerland", "149"),
        new KeyValuePair<string, string>("Syria", "285"),
        new KeyValuePair<string, string>("Taiwan", "152"),
        new KeyValuePair<string, string>("Tajikistan", "260"),
        new KeyValuePair<string, string>("Tanzania", "153"),
        new KeyValuePair<string, string>("Thailand", "154"),
        new KeyValuePair<string, string>("Togo", "155"),
        new KeyValuePair<string, string>("Tonga", "232"),
        new KeyValuePair<string, string>("Trinidad and Tobago", "234"),
        new KeyValuePair<string, string>("Tunisia", "156"),
        new KeyValuePair<string, string>("Turkey", "157"),
        new KeyValuePair<string, string>("Turks & Caicos Islands", "287"),
        new KeyValuePair<string, string>("Uganda", "159"),
        new KeyValuePair<string, string>("Ukraine", "161"),
        new KeyValuePair<string, string>("United Arab Emirates", "162"),
        new KeyValuePair<string, string>("United Kingdom", "262"),
        new KeyValuePair<string, string>("Uruguay", "163"),
        new KeyValuePair<string, string>("Uzbekistan", "165"),
        new KeyValuePair<string, string>("Vanuatu", "239"),
        new KeyValuePair<string, string>("Vatican City State (Holy See)", "166"),
        new KeyValuePair<string, string>("Venezuela", "167"),
        new KeyValuePair<string, string>("Vietnam", "168"),
        new KeyValuePair<string, string>("Virgin Islands (British)", "169"),
        new KeyValuePair<string, string>("Virgin Islands (U.S.)", "238"),
        new KeyValuePair<string, string>("Western Sahara", "188"),
        new KeyValuePair<string, string>("Yemen", "170"),
        new KeyValuePair<string, string>("Zambia", "173"),
        new KeyValuePair<string, string>("Zimbabwe", "174")
      }
      .AsReadOnly();
  }
}